# src/api/schemas/knowledge_base.py
from typing import Literal

from pydantic import BaseModel, Field


class AddKnowledgeBaseRequest(BaseModel):
    doc_id: str = Field(
        description="Unique document identifier generated by the Express backend."
    )
    file_path: str = Field(
        description="Absolute path to the file on shared storage. "
                    "The RAG service reads the file directly from this path."
    )
    file_name: str = Field(
        description="Original file name, stored in chunk metadata and returned in responses."
    )


class AddKnowledgeBaseResponse(BaseModel):
    doc_id: str = Field(
        description="Document identifier echoed from the request."
    )
    file_name: str = Field(
        description="Original file name echoed from the request."
    )
    chunks_indexed: int = Field(
        description="Number of chunks embedded and written to Chroma."
    )
    status: Literal["indexed"] = Field(
        description="Terminal status of the indexing operation."
    )


class DeleteKnowledgeBaseResponse(BaseModel):
    doc_id: str = Field(
        description="Document identifier that was deleted."
    )
    chunks_deleted: int = Field(
        description="Number of vectors removed from Chroma."
    )
    status: Literal["deleted"] = Field(
        description="Terminal status of the deletion operation."
    )